import { useMemo, useState } from 'react'
import { FiActivity, FiArrowLeft, FiBarChart2, FiBell, FiCalendar, FiCheck, FiChevronDown, FiClock, FiEdit3, FiGrid, FiHeart, FiLock, FiLogIn, FiMenu, FiPlus, FiSearch, FiSettings, FiShield, FiTarget, FiTrendingUp, FiUser, FiUsers, FiX, FiZap } from 'react-icons/fi'
import { publicResults } from './athletes.generated'
import './App.css'

type Sport='羽球'|'田徑'|'游泳'
type Athlete={id:string;name:string;sport:Sport;team:'男子組'|'女子組';grade:string;event:string;status:'公開賽事紀錄';load:number;school:string;junior:string;elementary:string;history:string;best:string;resultDate:string;source:string;sourceName:string;tags:string[]}
type Session={day:string;date:string;time:string;title:string;category:string;intensity:'低'|'中'|'高';duration:number;blocks:string[]}

const athletes:Athlete[]=publicResults.map((r,i)=>({id:`R${String(i+1).padStart(3,'0')}`,name:r.name,sport:r.sport,team:r.team,grade:'高中組',event:r.event,status:'公開賽事紀錄',load:0,school:r.school,junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:`113 年全中運 ${r.event}第 ${r.rank} 名${r.result?`，官方成績 ${r.result}`:''}。目前僅匯入此屆決賽紀錄。`,best:`${r.event} · 第 ${r.rank} 名${r.result?` · ${r.result}`:''}`,resultDate:'2024-04',source:r.source,sourceName:'113 年全國中等學校運動會官方決賽成績報告表',tags:[r.sport,r.team,`第 ${r.rank} 名`]}))
const initialSessions:Session[]=[
 {day:'一',date:'9/7',time:'16:00–18:30',title:'多球步伐 · 加速',category:'技術',intensity:'中',duration:150,blocks:['動態熱身 B','六點步伐 A','多球進攻 C']},
 {day:'二',date:'9/8',time:'16:00–18:00',title:'下肢力量 · 反應',category:'體能',intensity:'高',duration:120,blocks:['迷你頻帶 B','陷阱硬舉 A','燈號反應 C']},
 {day:'三',date:'9/9',time:'16:00–17:00',title:'恢復與個別課',category:'恢復',intensity:'低',duration:60,blocks:['活動度','呼吸放鬆']},
 {day:'四',date:'9/10',time:'16:00–18:30',title:'攻守轉換 · B 戰術',category:'戰術',intensity:'高',duration:150,blocks:['2 打 1','攻守轉換 B','限制區對抗']},
 {day:'五',date:'9/11',time:'14:00–17:00',title:'敏捷 · 速度 · 技術',category:'混合',intensity:'中',duration:180,blocks:['鬼抓人 C','敏捷階梯 B','10m 加速 A','網前對抗 D']},
]
const library=[
 {key:'熱身',icon:FiActivity,color:'cyan',items:['A 慢跑＋關節活動','B 動態伸展','C 鬼抓人','D 對抽熱身']},
 {key:'敏捷',icon:FiZap,color:'violet',items:['A 六角反應','B 敏捷階梯','C 鏡像移動','D 折返變向']},
 {key:'速度',icon:FiTrendingUp,color:'blue',items:['A 10m 加速','B 羽球步伐衝刺','C 電光起動','D 阻力帶加速']},
 {key:'力量',icon:FiBarChart2,color:'orange',items:['A 陷阱硬舉','B 保加利亞蹲','C 藥球旋轉拋','D 離心弓箭步']},
 {key:'戰術',icon:FiTarget,color:'green',items:['A 拉吊突擊','B 攻守轉換','C 雙打輪轉','D 發接發前三拍']},
 {key:'機能重建',icon:FiHeart,color:'red',items:['A 膝關節控制','B 肩胛穩定','C 踝關節本體感覺','D 返場移動']},
]
const sportModules:Record<Sport,Record<string,string[]>>={
 '羽球':{
  '移動與反應':['分腿墊步＋首步反應 4×20秒','六點步伐 4×45秒／休60秒','鏡像移動 4×15秒','隨機燈號啟動 6×5次'],
  '力量與功率':['陷阱槓硬舉 3×5／RPE 7','分腿蹲 3×8／側','藥球旋轉拋 4×5／側','低量側向增強式跳 3×5／側'],
  '專項體能':['多球間歇 6×45秒／休75秒','半場對抗 4×3分鐘','前後場轉換 5×30秒','發接發前三拍 8×6球']
 },
 '游泳':{
  '水中技術':['流線與出牆 8×15m','划手效率 8×25m 技術組','轉身＋水下 6×25m','呼吸節奏 6×50m'],
  '能量系統':['有氧基礎 6×200m／RPE 5','乳酸閾值 8×100m／RPE 7','速度 12×25m／充分恢復','比賽配速 6×50m'],
  '陸上肌力':['引體向上 3×6–10','單臂划船 3×8／側','反旋轉推壓 3×10／側','肩胛控制＋旋轉肌群 2×12']
 },
 '田徑':{
  '短距離':['加速跑 6×20m／全恢復','飛行跑 4×30m','起跑反應 6×1次','速度耐力 3×120m／長休'],
  '中距離':['節奏跑 4×400m／RPE 7','有氧間歇 5×800m','跑姿經濟性 drills 12分鐘','末段速度 6×150m'],
  '長距離':['低強度有氧 35–60分鐘','乳酸閾值 3×8分鐘','坡跑 8×45秒','長間歇 5×1000m'],
  '跳部':['助跑節奏 8次','低量跨步跳 3×20m','起跳技術 6×3次','深蹲跳 3×5／充分休息'],
  '擲部':['藥球前拋 4×5','旋轉分解 6×3次','深蹲 3×5／RPE 7','推舉 3×5／技術優先'],
  '全能':['速度＋欄架技術','跳躍技術交替日','投擲技術低量練習','恢復監測與賽程模擬']
 }
}
const nav=[['dashboard','總覽',FiGrid],['athletes','選手管理',FiUsers],['schedule','訓練課表',FiCalendar],['library','課表資料庫',FiBarChart2],['cycles','週期管理',FiTrendingUp],['rebuild','機能重建',FiHeart]] as const

function App(){
 const [loggedIn,setLoggedIn]=useState(()=>sessionStorage.getItem('ams-demo-login')==='yes');const [active,setActive]=useState('dashboard');const [sport,setSport]=useState<Sport|'全部'>('全部');const [school,setSchool]=useState('全部');const [query,setQuery]=useState('');const [builder,setBuilder]=useState(false);const [mobile,setMobile]=useState(false);const [selected,setSelected]=useState<Athlete|null>(null);const [notice,setNotice]=useState('')
 const [blocks,setBlocks]=useState<string[]>(()=>{const d=localStorage.getItem('ams-friday-draft');try{return d?JSON.parse(d):['C 鬼抓人','B 敏捷階梯','A 10m 加速','D 網前對抗']}catch{return[]}})
 const [sessions,setSessions]=useState<Session[]>(()=>{const d=localStorage.getItem('ams-sessions-v1');try{return d?JSON.parse(d):initialSessions}catch{return initialSessions}})
 const visible=useMemo(()=>athletes.filter(a=>(sport==='全部'||a.sport===sport)&&(school==='全部'||a.school===school)&&`${a.name}${a.event}${a.tags}${a.school}${a.sport}`.includes(query)),[sport,school,query])
 const enter=()=>{sessionStorage.setItem('ams-demo-login','yes');setLoggedIn(true)};const logout=()=>{sessionStorage.removeItem('ams-demo-login');setLoggedIn(false)}
 const flash=(text:string)=>{setNotice(text);setTimeout(()=>setNotice(''),2200)}
 if(!loggedIn)return <Login onEnter={enter}/>
 return <div className="shell">
  <aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><b><FiActivity/></b><div><strong>運動員管理系統</strong><span>Taipei Sports Science Center</span></div><button onClick={()=>setMobile(false)}><FiX/></button></div><div className="club"><i>北</i><div><span>系統角色</span><strong>臺北市運動科學中心</strong></div></div><nav><small>中心工作台</small>{nav.map(([id,label,Icon])=><button className={active===id?'active':''} key={id} onClick={()=>{setActive(id);setSelected(null);setMobile(false)}}><Icon/><span>{label}</span>{id==='rebuild'&&<i>示範</i>}</button>)}</nav><div className="side-bottom"><button onClick={()=>flash('教學版尚未開放權限管理')}><FiShield/>健康與權限</button><button onClick={()=>flash('系統設定已保留給正式治理版本')}><FiSettings/>系統設定</button><button className="coach" onClick={logout}><i>教</i><div><strong>教學示範帳號</strong><span>點此登出</span></div></button></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>} 
  <main><header className="top"><button className="menu" onClick={()=>setMobile(true)}><FiMenu/></button><label className="search"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋運動、學校、選手或項目…"/></label><button className="bell"><FiBell/></button><span className="sync"><i/>教學版 · 公開賽事資料</span></header><div className="content">{selected?<AthleteDetail athlete={selected} onBack={()=>setSelected(null)}/>:<Page active={active} sport={sport} setSport={setSport} school={school} setSchool={setSchool} athletes={visible} sessions={sessions} setSelected={setSelected} setBuilder={setBuilder} flash={flash}/>}</div><SiteNotice/></main>
  {notice&&<div className="toast"><FiCheck/>{notice}</div>}{builder&&<Builder blocks={blocks} setBlocks={setBlocks} close={()=>setBuilder(false)} flash={flash} onCreate={s=>{const next=[...sessions,s];setSessions(next);localStorage.setItem('ams-sessions-v1',JSON.stringify(next))}}/>}
 </div>
}

function Login({onEnter}:{onEnter:()=>void}){const schools=new Set(athletes.map(a=>a.school)).size;return <main className="login"><section className="login-copy"><div className="login-brand"><i><FiActivity/></i><strong>運動員管理系統</strong><span>臺北市運動科學中心情境示範</span></div><div><span className="demo-chip">AI 工具教學版 · 非營運系統</span><h1>從公開賽事紀錄，建立<br/>選手歷程與科學支援視角。</h1><p>以臺北市高中羽球、田徑與游泳為資料架構範例，示範中心如何連結選手歷程、檢測方向與訓練資源。</p><div className="login-stats"><span><b>3</b>項運動</span><span><b>{athletes.length}</b>筆官方決賽紀錄</span><span><b>{schools}</b>所學校</span></div><div className="purpose"><FiShield/><p><strong>使用用途聲明</strong>本系統僅提供 AI 工具教學使用，不開放教練或選手後續私下使用，亦不對外提供開放使用，僅供教學用途。</p></div></div><footer>製作單位：臺灣運動健康科技學會 · 教學版 v0.4</footer></section><section className="login-card"><div className="login-icon"><FiUser/></div><span className="eyebrow">中心教學工作台</span><h2>進入系統示範</h2><p>不需要帳號密碼；資料不代表現役完整名單。</p><div className="demo-user"><i>北</i><div><strong>臺北市運動科學中心</strong><span>教學情境 · 唯讀公開資料</span></div><FiCheck/></div><button className="login-button" onClick={onEnter}><FiLogIn/>進入運動員管理系統</button><div className="login-note"><FiLock/><span><strong>隱私邊界</strong>未公開學歷、傷病與檢測資料一律不推測，須經本人及管理單位授權後補登。</span></div></section></main>}

function Page({active,sport,setSport,school,setSchool,athletes:shown,sessions,setSelected,setBuilder,flash}:{active:string;sport:Sport|'全部';setSport:(x:Sport|'全部')=>void;school:string;setSchool:(x:string)=>void;athletes:Athlete[];sessions:Session[];setSelected:(a:Athlete)=>void;setBuilder:(x:boolean)=>void;flash:(x:string)=>void}){
 if(active==='dashboard')return <Dashboard setSelected={setSelected}/>
 const meta:Record<string,[string,string]>={athletes:['臺北市高中選手資料庫','依運動、學校與姓名查詢公開賽事歷史紀錄'],schedule:['運動處方與訓練課表','以中心檢測結果連結運動處方與隊伍訓練'],library:['處方模組資料庫','24 個熱身、體能、戰術與機能重建示範模組'],cycles:['週期管理','用大週期、中週期與小週期銜接學校賽事需求'],rebuild:['中心服務流程','從歷程盤點、檢測到教練協作的教學示範']};const [title,sub]=meta[active]
 return <><section className="heading inner-heading"><div><small>臺北市運動科學中心 · AI 工具教學版</small><h1>{title}</h1><p>{sub}</p></div>{active==='schedule'&&<button className="primary" onClick={()=>setBuilder(true)}><FiPlus/>新增處方課表</button>}</section>
 {active==='athletes'&&<><DatabaseFilters sport={sport} setSport={setSport} school={school} setSchool={setSchool}/><div className="data-scope"><FiShield/><span>目前收錄 113 年全中運官方決賽表中，臺北市高中組羽球、田徑、游泳共 <b>{athletes.length} 筆公開成績紀錄</b>、{new Set(athletes.map(a=>a.school)).size} 所學校；不是全市現役完整名單。資料查詢日：2026-09-08。</span></div><AthleteCards list={shown} select={setSelected}/></>} {active==='schedule'&&<Schedule sessions={sessions} setBuilder={setBuilder}/>} {active==='library'&&<Library setBuilder={setBuilder}/>} {active==='cycles'&&<Cycles/>} {active==='rebuild'&&<RebuildWorkspace flash={flash}/>}</>
}

function Dashboard({setSelected}:{setSelected:(a:Athlete)=>void}){const schools=new Set(athletes.map(a=>a.school)).size;return <><section className="heading"><div><small>城市級運動科學支援 · 教學情境</small><h1>臺北市高中選手歷程總覽</h1><p>從官方成績找到選手，再以授權資料完成檢測、處方與教練協作。</p></div></section><section className="metrics"><article><i className="purple"><FiUsers/></i><div><span>公開決賽紀錄</span><strong>{athletes.length}</strong><small>113 年全中運範圍</small></div></article><article><i className="cyan"><FiActivity/></i><div><span>示範運動</span><strong>3</strong><small>羽球 · 田徑 · 游泳</small></div></article><article><i className="orange"><FiGrid/></i><div><span>涵蓋學校</span><strong>{schools}</strong><small>依官方賽事單位彙整</small></div></article><article><i className="red"><FiShield/></i><div><span>私人健康資料</span><strong>0</strong><small>未授權不匯入</small></div></article></section><section className="sport-overview">{(['羽球','田徑','游泳'] as Sport[]).map((s,i)=>{const list=athletes.filter(a=>a.sport===s);return <article className={'sport-card sport-'+i} key={s}><header><i>{i===0?'羽':i===1?'徑':'泳'}</i><div><span>高中組</span><h2>{s}</h2></div><b>{list.length} 筆</b></header><p>{new Set(list.map(a=>a.school)).size} 所學校 · 113 年全中運決賽</p><div>{list.slice(0,4).map(a=><button key={a.id} onClick={()=>setSelected(a)}><span>{a.name}</span><small>{a.school} · {a.event}</small><b>→</b></button>)}<small className="more-records">另有 {Math.max(0,list.length-4)} 筆，請至選手管理查詢</small></div></article>})}</section><section className="panel pathway"><PanelHead title="中心服務判斷路徑" sub="公開歷程不等於醫療結論；到中心後才建立個別化支援"/><div><span><b>1</b>官方賽事歷程<small>確認項目與成績趨勢</small></span><i>→</i><span><b>2</b>本人授權訪談<small>學校歷程、傷病與訓練背景</small></span><i>→</i><span><b>3</b>運動科學檢測<small>依需求選擇體能與技術指標</small></span><i>→</i><span><b>4</b>處方與資源協作<small>與選手、教練共同決策</small></span></div></section></>}

function DatabaseFilters({sport,setSport,school,setSchool}:{sport:Sport|'全部';setSport:(x:Sport|'全部')=>void;school:string;setSchool:(x:string)=>void}){const schools=['全部',...new Set(athletes.filter(a=>sport==='全部'||a.sport===sport).map(a=>a.school))];return <div className="db-filters"><label>運動項目<select value={sport} onChange={e=>{setSport(e.target.value as Sport|'全部');setSchool('全部')}}><option>全部</option><option>羽球</option><option>田徑</option><option>游泳</option></select></label><label>所屬學校<select value={school} onChange={e=>setSchool(e.target.value)}>{schools.map(x=><option key={x}>{x}</option>)}</select></label></div>}

function AthleteCards({list,select}:{list:Athlete[];select:(a:Athlete)=>void}){return <div className="athlete-cards">{list.length?list.map(a=><button key={a.id} className="athlete-card" onClick={()=>select(a)}><header><i>{a.sport[0]}</i><span className="status public">公開紀錄</span></header><h2>{a.name}</h2><p>{a.school} · {a.grade} · {a.event}</p><div className="athlete-kpis"><span><small>運動</small><b>{a.sport}</b></span><span><small>資料日期</small><b>{a.resultDate}</b></span></div><div className="tags">{a.tags.map(t=><i key={t}>{t}</i>)}</div><footer>查看歷程檔案 <span>→</span></footer></button>):<div className="empty">沒有符合目前條件的公開紀錄。</div>}</div>}
function AthleteDetail({athlete:a,onBack}:{athlete:Athlete;onBack:()=>void}){return <><button className="back" onClick={onBack}><FiArrowLeft/>回到選手資料庫</button><section className="profile-hero"><i>{a.sport[0]}</i><div><span>{a.id} · {a.sport} · {a.team}</span><h1>{a.name}</h1><p>{a.school} · {a.grade} · {a.event}</p></div><b className="status public">官方公開賽事紀錄</b></section><div className="profile-grid"><section className="panel profile-section"><PanelHead title="基本與學校歷程" sub="未公開欄位不推測"/><dl><div><dt>目前紀錄單位</dt><dd>{a.school}</dd></div><div><dt>運動／主項</dt><dd>{a.sport} · {a.event}</dd></div><div><dt>過去國中</dt><dd>{a.junior}</dd></div><div><dt>過去國小</dt><dd>{a.elementary}</dd></div></dl></section><section className="panel profile-section"><PanelHead title="賽事與成績" sub="已連結官方原始資料"/><div className="result"><FiTarget/><div><strong>{a.best}</strong><span>{a.resultDate} · <a href={a.source} target="_blank" rel="noreferrer">查看官方來源 ↗</a></span></div></div></section><section className="panel profile-section"><PanelHead title="過去歷程分析" sub="只根據目前已匯入的官方賽事"/><div className="health"><FiTrendingUp/><span>{a.history}</span></div></section><section className="panel profile-section"><PanelHead title="到中心後待建資料" sub="須取得授權並由專業人員建立"/><div className="tags big">{['傷病史訪談','體能測驗','技術／得意技','訓練負荷','檢測方向','運動處方'].map(t=><i key={t}>{t}</i>)}</div><p className="privacy-note">目前沒有私人健康或體能測驗資料；不可由公開成績推定傷病、體能或技術弱點。</p></section></div><section className="source-ledger"><FiShield/><div><strong>來源台帳</strong><span>{a.sourceName} · 賽事日期 {a.resultDate} · 查詢日期 2026-09-08 · 信心：官方已確認</span></div></section></>}
function Schedule({sessions,setBuilder}:{sessions:Session[];setBuilder:(x:boolean)=>void}){const hours=(sessions.reduce((n,s)=>n+s.duration,0)/60).toFixed(1);return <section className="panel"><PanelHead title="本週課表" sub={`${sessions.length} 天訓練 · 共 ${hours} 小時`}><button className="primary" onClick={()=>setBuilder(true)}><FiPlus/>新增第 {sessions.length+1} 天</button></PanelHead><WeekList sessions={sessions} setBuilder={setBuilder}/></section>}
function WeekList({sessions,setBuilder}:{sessions:Session[];setBuilder:(x:boolean)=>void}){return <div className="week-list">{sessions.map((s,index)=><article key={`${s.date}-${index}`}><div className={index===sessions.length-1?'day today':'day'}><small>{s.day.startsWith('第')?s.day:`週${s.day}`}</small><strong>{s.date.split('/').pop()}</strong></div><div className="session"><div><span className={'cat '+s.category}>{s.category}</span><strong>{s.title}</strong></div><p><FiClock/> {s.time} · {s.duration} 分鐘</p><footer>{s.blocks.map(x=><i key={x}>{x}</i>)}</footer></div><span className={'level '+s.intensity}><i/>{s.intensity}強度</span><button onClick={()=>setBuilder(true)} aria-label="編輯課表"><FiEdit3/></button></article>)}<button className="add-day" onClick={()=>setBuilder(true)}><FiPlus/>新增第 {sessions.length+1} 天課表</button></div>}
function Library({setBuilder}:{setBuilder:(x:boolean)=>void}){const [sport,setSport]=useState<Sport>('羽球');return <><div className="evidence-banner"><FiShield/><div><strong>專業設計依據</strong><p>模組依 ACSM 青少年阻力訓練安全原則與 NSCA 課表設計架構整理；實際負荷須由合格專業人員依訓練年齡、技術、測驗及賽期個別調整。</p></div><a href="https://www.nsca.com/certification/cscs/essentials-of-strength-training-and-conditioning-5th-edition/" target="_blank" rel="noreferrer">NSCA 來源 ↗</a></div><div className="sport-tabs">{(['羽球','游泳','田徑'] as Sport[]).map(s=><button className={sport===s?'on':''} onClick={()=>setSport(s)} key={s}>{s}</button>)}</div><div className="module-sections">{Object.entries(sportModules[sport]).map(([key,items],group)=><section className="panel module-group" key={key}><header><i className={['violet','cyan','orange','blue','green','red'][group%6]}><FiActivity/></i><div><h2>{key}</h2><p>{items.length} 個處方模組</p></div></header>{items.map((item,i)=><button key={item} onClick={()=>setBuilder(true)}><span>{item}</span><small>{i%2?'中等':'技術優先'} · 可調劑量</small><FiPlus/></button>)}</section>)}</div><div className="library-notes"><a href="https://www.acsm.org/wp-content/uploads/2025/02/NYSHSI-Youth-Resistance-Training-PDF.pdf" target="_blank" rel="noreferrer">ACSM 青少年阻力訓練指引 ↗</a><span>先動作品質，再加負荷；由簡至繁、輕至重、穩定至爆發。</span><span>NSCA 架構：需求分析 → 動作選擇 → 頻率 → 順序 → 負荷／反覆次數 → 總量 → 休息。</span></div></>}
function Cycles(){const [scope,setScope]=useState('整隊');const [sport,setSport]=useState<Sport>('羽球');const [gender,setGender]=useState('男子組');const [school,setSchool]=useState('大同高中');const [athlete,setAthlete]=useState('');const [loads,setLoads]=useState(['中','高','低','高','中','低','休']);const save=()=>localStorage.setItem('ams-cycle-v1',JSON.stringify({scope,sport,gender,school,athlete,loads}));return <div className="cycles-page"><section className="panel cycle-controls"><PanelHead title="週期對象" sub="可開整隊、男／女組或個人週期"/><div className="cycle-form"><label>層級<select value={scope} onChange={e=>setScope(e.target.value)}><option>整隊</option><option>個人</option></select></label><label>單位<select value={school} onChange={e=>setSchool(e.target.value)}>{[...new Set(athletes.map(a=>a.school))].map(x=><option key={x}>{x}</option>)}</select></label><label>運動<select value={sport} onChange={e=>setSport(e.target.value as Sport)}><option>羽球</option><option>田徑</option><option>游泳</option></select></label><label>組別<select value={gender} onChange={e=>setGender(e.target.value)}><option>男子組</option><option>女子組</option></select></label>{scope==='個人'&&<label>選手<select value={athlete} onChange={e=>setAthlete(e.target.value)}><option value="">選擇選手</option>{athletes.filter(a=>a.school===school&&a.sport===sport&&a.team===gender).map(a=><option key={a.id}>{a.name}</option>)}</select></label>}<button className="primary" onClick={()=>{save();alert('週期設定已儲存在本機')}}>儲存週期設定</button></div></section><section className="panel cycle-overview"><PanelHead title={`大週期 · ${school} ${sport}${scope==='整隊'?gender:athlete||'個人'}`} sub="年度賽事準備示範"/><div className="macro"><div className="phase p1"><b>一般準備期</b><span>動作品質 · 基礎體能</span></div><div className="phase p2"><b>專項準備期</b><span>力量／速度 · 專項量</span></div><div className="phase p3"><b>賽前期</b><span>比賽強度 · 減量</span></div><div className="phase p4"><b>競賽／轉換</b><span>表現 · 恢復</span></div></div></section><section className="panel current-cycle"><PanelHead title="目前中週期" sub="4 週建立＋1 週調整的示範區塊"/><CycleCore/></section><section className="panel micro"><PanelHead title="本週小週期" sub="點擊每一天切換負荷"/><div>{loads.map((x,i)=><button key={i} onClick={()=>setLoads(v=>v.map((z,j)=>j===i?z==='低'?'中':z==='中'?'高':z==='高'?'休':'低':z))}><b>週{['一','二','三','四','五','六','日'][i]}</b><i className={x}>{x}</i></button>)}</div></section></div>}
function CycleCore(){return <><div className="cycle-main"><div className="cycle-ring"><span><b>3</b>/ 8 週</span></div><div><strong>中週期 1</strong><p>體能建立期</p><small>9/1 — 10/25</small></div></div><div className="phases"><span>適應</span><span>建立</span><span>轉換</span><span>競賽</span></div><div className="focus"><small>本週重點</small><strong>下肢力量 · 加速能力</strong><p>體能 45% / 技戰術 55%</p></div></>}
function RebuildWorkspace({flash}:{flash:(x:string)=>void}){
 const [school,setSchool]=useState('大同高中');const [sport,setSport]=useState<Sport>('羽球');const [person,setPerson]=useState('');const [stage,setStage]=useState('初篩');const [current,setCurrent]=useState('');const [pathology,setPathology]=useState('');const [checks,setChecks]=useState<Record<string,boolean>>({});const [notes,setNotes]=useState('');
 const screening=['靜止與活動疼痛已記錄（0–10）','步行／日常活動可耐受','全蹲動作品質可接受','弓箭步左右可控制','雙手上舉可達耳旁且無代償','單腳平衡 30 秒','低階跳躍／落地（適用時）','運動員信心與準備度已詢問'];
 const stagePlans:Record<string,string[]>= {'初篩':['症狀與紅旗確認','活動度／基本動作','轉介或進入 ADL'],ADL:['無痛步行與樓梯','基礎蹲／推／拉','低負荷有氧'],低強度:['CKC：箱式深蹲、分腿蹲','OKC：膝伸／屈或肩旋轉控制','草地／緩衝墊；不安排跳躍衝擊'],中強度:['小幅雙腳跳與落地','漸進加速／減速','限制方向與總接觸次數'],高強度:['單腳跳與變向','專項速度與反應','羽球米字跑／泳姿出發／田徑專項銜接'],回隊評估:['完成完整修改訓練','專項功能與信心複測','共同決策：回隊／維持個訓／轉介']};
 const eligible=athletes.filter(a=>a.school===school&&a.sport===sport);
 const save=()=>{localStorage.setItem('ams-rebuild-v1',JSON.stringify({school,sport,person,stage,current,pathology,checks,notes,updatedAt:new Date().toISOString()}));flash('機能重建紀錄已儲存在這台裝置')};
 return <div className="rebuild-workspace"><section className="panel"><PanelHead title="1. 人員與項目選擇" sub="機能重建以個人紀錄為主"/><div className="cycle-form"><label>單位<select value={school} onChange={e=>{setSchool(e.target.value);setPerson('')}}>{[...new Set(athletes.map(a=>a.school))].map(x=><option key={x}>{x}</option>)}</select></label><label>運動<select value={sport} onChange={e=>{setSport(e.target.value as Sport);setPerson('')}}><option>羽球</option><option>田徑</option><option>游泳</option></select></label><label>選手<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">請選擇個人</option>{eligible.map(a=><option key={a.id}>{a.name}｜{a.event}</option>)}</select></label></div></section><section className="panel"><PanelHead title="2. 現況與病理評估" sub="病理診斷僅由合格醫療專業人員填寫"/><div className="assessment-grid"><label>目前狀況<textarea value={current} onChange={e=>setCurrent(e.target.value)} placeholder="症狀、疼痛、負荷反應、目前可完成活動…"/></label><label>病理／醫療評估<textarea value={pathology} onChange={e=>setPathology(e.target.value)} placeholder="若尚無正式診斷請填『待醫療評估』，不要自行診斷。"/></label></div></section><section className="panel screening"><PanelHead title="3. 簡易功能初篩" sub="這是記錄清單，不是診斷；紅旗、明顯疼痛或神經症狀應停止並轉介"/><div>{screening.map(x=><label key={x}><input type="checkbox" checked={!!checks[x]} onChange={e=>setChecks(v=>({...v,[x]:e.target.checked}))}/><span>{x}</span></label>)}</div></section><section className="panel stage-panel"><PanelHead title="4. 復健與運動機能重建階段" sub="採條件式漸進，不只看經過幾週"/><div className="stage-tabs">{Object.keys(stagePlans).map(x=><button className={stage===x?'on':''} onClick={()=>setStage(x)} key={x}>{x}</button>)}</div><div className="stage-content"><div><small>目前階段</small><h2>{stage}</h2><p>{stage==='高強度'?'逐漸接近正常專項訓練，但仍須監測反應。':'達成該階段條件後再前進，不以時間自動升級。'}</p></div><ul>{stagePlans[stage].map(x=><li key={x}><FiCheck/>{x}</li>)}</ul></div></section><section className="panel"><PanelHead title="5. 簡易測驗、評估與交接" sub="參考 return-to-sport continuum 與 PAASS 多領域概念"/><div className="assessment-grid"><label>測驗結果與左右差異<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="紀錄疼痛、ROM、力量／耐力／功率、平衡、跳躍、敏捷、專項訓練完成度與信心…"/></label><div className="decision-box"><strong>團隊共同決策</strong><label><input type="radio" name="decision"/>回到正常隊伍訓練</label><label><input type="radio" name="decision"/>維持修改後訓練</label><label><input type="radio" name="decision"/>個別體能／防護訓練</label><label><input type="radio" name="decision"/>轉介醫師／物理治療師</label></div></div><footer className="record-actions"><a href="https://bjsm.bmj.com/content/50/14/853" target="_blank" rel="noreferrer">Return-to-sport 共識來源 ↗</a><button className="primary" onClick={save}>儲存本次紀錄</button></footer></section></div>
}
function Builder({blocks,setBlocks,close,flash,onCreate}:{blocks:string[];setBlocks:React.Dispatch<React.SetStateAction<string[]>>;close:()=>void;flash:(x:string)=>void;onCreate:(s:Session)=>void}){
 const [date,setDate]=useState('2026-09-12');const [start,setStart]=useState('09:00');const [end,setEnd]=useState('11:00');const [title,setTitle]=useState('新增訓練日');
 const minutes=Math.max(0,(Number(end.split(':')[0])*60+Number(end.split(':')[1]))-(Number(start.split(':')[0])*60+Number(start.split(':')[1])));
 const save=()=>{localStorage.setItem('ams-friday-draft',JSON.stringify(blocks));flash('教學草稿已儲存在這台裝置')};
 const create=()=>{if(!date||minutes<=0||blocks.length===0){flash('請確認日期、時間與至少一個訓練模組');return}onCreate({day:`第新增日`,date:date.slice(5).replace('-','/'),time:`${start}–${end}`,title,category:'混合',intensity:'中',duration:minutes,blocks});flash('新訓練日已加入本週課表');close()};
 return <div className="modal"><button className="modal-bg" onClick={close}/><section role="dialog" aria-modal="true"><header><div><p>臺北市運動科學中心 · 教學情境</p><h2>新增運動處方課表</h2></div><button onClick={close}><FiX/></button></header><main><div className="fields"><label>日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>開始<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>結束<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>課表名稱<input value={title} onChange={e=>setTitle(e.target.value)}/></label></div><div className="summary"><FiClock/><div><strong>{title} · {minutes} 分鐘</strong><span>建立後會往下新增，不再限制五天</span></div></div><div className="builder-grid"><div className="picker"><h3>1. 從資料庫加入</h3><p>點選即可加入流程</p>{library.map(({key,items,icon:Icon,color})=><details key={key} open={key==='熱身'}><summary><i className={color}><Icon/></i><strong>{key}</strong><FiChevronDown/></summary><div>{items.map(item=><button onClick={()=>setBlocks(v=>v.includes(item)?v:[...v,item])} key={item}><FiPlus/>{item}</button>)}</div></details>)}</div><div className="timeline"><h3>2. 訓練流程</h3><p>已選 {blocks.length} 個模組</p>{blocks.map((b,i)=><div className="block" key={b}><i>{i+1}</i><div><strong>{b}</strong><span>{i===0?'熱身 · 20 分':'主訓練 · 30 分'}</span></div><button onClick={()=>setBlocks(v=>v.filter((_,x)=>x!==i))}><FiX/></button></div>)}</div></div></main><footer><span>教學版僅將課表保存在本機瀏覽器</span><div><button className="secondary" onClick={save}>儲存草稿</button><button className="primary" onClick={create}>建立並新增一天</button></div></footer></section></div>
}
function SiteNotice(){return <footer className="site-notice"><span>製作單位：臺灣運動健康科技學會</span><p>本系統僅提供 AI 工具教學使用，不開放教練或選手後續私下使用，亦不對外提供開放使用，僅供教學用途。</p></footer>}
function PanelHead({title,sub,children}:{title:string;sub:string;children?:React.ReactNode}){return <header className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div>{children}</header>}
export default App
