import { useMemo, useState } from 'react'
import { FiActivity, FiArrowLeft, FiBarChart2, FiBell, FiCalendar, FiCheck, FiChevronDown, FiClock, FiEdit3, FiGrid, FiHeart, FiLock, FiLogIn, FiMenu, FiPlus, FiSearch, FiSettings, FiShield, FiTarget, FiTrendingUp, FiUser, FiUsers, FiX, FiZap } from 'react-icons/fi'
import './App.css'

type Athlete={id:string;name:string;team:'男生隊'|'女生隊';grade:string;event:string;status:'正常'|'調整'|'重建';load:number;school:string;height:number;weight:number;hand:string;history:string;best:string;tags:string[]}
type Session={day:string;date:string;time:string;title:string;category:string;intensity:'低'|'中'|'高';duration:number;blocks:string[]}

const athletes:Athlete[]=[
 {id:'A001',name:'林子翔',team:'男生隊',grade:'高二',event:'男單',status:'正常',load:78,school:'大同高中',height:176,weight:67,hand:'右手',history:'無重大傷病',best:'2026 臺北市中運男單 8 強',tags:['速度型','網前積極','加強後場穩定']},
 {id:'A002',name:'陳信宇',team:'男生隊',grade:'高一',event:'男雙',status:'調整',load:64,school:'大同高中',height:181,weight:72,hand:'右手',history:'右肩過度使用（示範）',best:'2026 全中運男雙 16 強',tags:['後場進攻','右肩觀察','發接發加強']},
 {id:'A003',name:'黃宜庭',team:'女生隊',grade:'高二',event:'女單',status:'正常',load:72,school:'大同高中',height:168,weight:57,hand:'左手',history:'左踝舊傷，目前無症狀（示範）',best:'2026 臺北市中運女單 4 強',tags:['防守反擊','多拍穩定','提高主動進攻']},
]
const sessions:Session[]=[
 {day:'一',date:'9/7',time:'16:00–18:30',title:'多球步伐 · 加速',category:'技術',intensity:'中',duration:150,blocks:['動態熱身 B','六點步伐 A','多球進攻 C']},
 {day:'二',date:'9/8',time:'16:00–18:00',title:'下肢力量 · 反應',category:'體能',intensity:'高',duration:120,blocks:['迷你頻帶 B','陷阱硬舉 A','燈號反應 C']},
 {day:'三',date:'9/9',time:'16:00–17:00',title:'恢復與個別課',category:'恢復',intensity:'低',duration:60,blocks:['活動度','呼吸放鬆']},
 {day:'四',date:'9/10',time:'16:00–18:30',title:'攻守轉換 · B 戰術',category:'戰術',intensity:'高',duration:150,blocks:['2 打 1','攻守轉換 B','限制區對抗']},
 {day:'五',date:'9/11',time:'14:00–17:00',title:'敏捷 · 速度 · 技術',category:'混合',intensity:'中',duration:180,blocks:['鬼抓人 C','敏捷階梯 B','10m 加速 A','網前對抗 D']},
]
const library=[
 {key:'熱身',icon:FiActivity,color:'cyan',items:['A 慢跑＋關節活動','B 動態伸展','C 鬼抓人','D 對抽熱身']},
 {key:'敏捷',icon:FiZap,color:'violet',items:['A 六角反應','B 敏捷階梯','C 鏡像移動','D 折返變向']},
 {key:'速度',icon:FiTrendingUp,color:'blue',items:['A 10m 加速','B 羽球步伐衝刺','C 電光起動','D 阻力帶加速']},
 {key:'力量',icon:FiBarChart2,color:'orange',items:['A 陷阱硬舉','B 保加利亞蹲','C 藥球旋轉拋','D 離心弓箭步']},
 {key:'戰術',icon:FiTarget,color:'green',items:['A 拉吊突擊','B 攻守轉換','C 雙打輪轉','D 發接發前三拍']},
 {key:'機能重建',icon:FiHeart,color:'red',items:['A 膝關節控制','B 肩胛穩定','C 踝關節本體感覺','D 返場移動']},
]
const nav=[['dashboard','總覽',FiGrid],['athletes','選手管理',FiUsers],['schedule','訓練課表',FiCalendar],['library','課表資料庫',FiBarChart2],['cycles','週期管理',FiTrendingUp],['rebuild','機能重建',FiHeart]] as const

function App(){
 const [loggedIn,setLoggedIn]=useState(()=>sessionStorage.getItem('ams-demo-login')==='yes');const [active,setActive]=useState('dashboard');const [team,setTeam]=useState<'男生隊'|'女生隊'>('男生隊');const [query,setQuery]=useState('');const [builder,setBuilder]=useState(false);const [mobile,setMobile]=useState(false);const [selected,setSelected]=useState<Athlete|null>(null);const [notice,setNotice]=useState('')
 const [blocks,setBlocks]=useState<string[]>(()=>{const d=localStorage.getItem('ams-friday-draft');try{return d?JSON.parse(d):['C 鬼抓人','B 敏捷階梯','A 10m 加速','D 網前對抗']}catch{return[]}})
 const visible=useMemo(()=>athletes.filter(a=>(team===a.team||active==='athletes')&&`${a.name}${a.event}${a.tags}`.includes(query)),[team,query,active])
 const enter=()=>{sessionStorage.setItem('ams-demo-login','yes');setLoggedIn(true)};const logout=()=>{sessionStorage.removeItem('ams-demo-login');setLoggedIn(false)}
 const flash=(text:string)=>{setNotice(text);setTimeout(()=>setNotice(''),2200)}
 if(!loggedIn)return <Login onEnter={enter}/>
 return <div className="shell">
  <aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><b><FiActivity/></b><div><strong>AMS</strong><span>Athletic Intelligence</span></div><button onClick={()=>setMobile(false)}><FiX/></button></div><div className="club"><i>同</i><div><span>目前隊伍</span><strong>大同高中羽球隊</strong></div><FiChevronDown/></div><nav><small>工作台</small>{nav.map(([id,label,Icon])=><button className={active===id?'active':''} key={id} onClick={()=>{setActive(id);setSelected(null);setMobile(false)}}><Icon/><span>{label}</span>{id==='rebuild'&&<i>1</i>}</button>)}</nav><div className="side-bottom"><button onClick={()=>flash('測試版尚未開放權限管理')}><FiShield/>健康與權限</button><button onClick={()=>flash('系統設定已保留給正式版')}><FiSettings/>系統設定</button><button className="coach" onClick={logout}><i>張</i><div><strong>測試教練</strong><span>點此登出測試版</span></div></button></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>} 
  <main><header className="top"><button className="menu" onClick={()=>setMobile(true)}><FiMenu/></button><label className="search"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋選手、課表或訓練項目…"/></label><button className="bell"><FiBell/><i/></button><span className="sync"><i/>測試版 · 本機資料</span></header><div className="content">{selected?<AthleteDetail athlete={selected} onBack={()=>setSelected(null)}/>:<Page active={active} team={team} setTeam={setTeam} athletes={visible} setSelected={setSelected} setBuilder={setBuilder} flash={flash}/>}</div></main>
  {notice&&<div className="toast"><FiCheck/>{notice}</div>}{builder&&<Builder blocks={blocks} setBlocks={setBlocks} close={()=>setBuilder(false)} flash={flash}/>} 
 </div>
}

function Login({onEnter}:{onEnter:()=>void}){return <main className="login"><section className="login-copy"><div className="login-brand"><i><FiActivity/></i><strong>AMS</strong><span>Athletic Intelligence</span></div><div><span className="demo-chip">大同高中羽球隊 · 測試環境</span><h1>把選手狀態、訓練週期<br/>與每一堂課，放在同一個地方。</h1><p>為教練打造的運動員管理系統。從今日訓練到長期發展，每個決定都更清楚。</p><div className="login-stats"><span><b>3</b>位範例選手</span><span><b>24</b>個訓練模組</span><span><b>1</b>套週期計畫</span></div></div><footer>測試版 v0.2 · 所有選手資料均為虛構示範</footer></section><section className="login-card"><div className="login-icon"><FiUser/></div><span className="eyebrow">教練工作台</span><h2>歡迎回來</h2><p>目前是功能測試版，不需要帳號密碼。</p><div className="demo-user"><i>張</i><div><strong>測試教練</strong><span>大同高中羽球隊 · 管理檢視</span></div><FiCheck/></div><button className="login-button" onClick={onEnter}><FiLogIn/>進入 AMS 測試系統</button><div className="login-note"><FiLock/><span><strong>無需密碼</strong>此版本不會建立帳號，也不會將您輸入的資料同步到雲端。</span></div></section></main>}

function Page({active,team,setTeam,athletes,setSelected,setBuilder,flash}:{active:string;team:'男生隊'|'女生隊';setTeam:(x:'男生隊'|'女生隊')=>void;athletes:Athlete[];setSelected:(a:Athlete)=>void;setBuilder:(x:boolean)=>void;flash:(x:string)=>void}){
 if(active==='dashboard')return <Dashboard team={team} setTeam={setTeam} setBuilder={setBuilder} setSelected={setSelected}/>
 const meta:Record<string,[string,string]>={athletes:['選手管理','3 位虛構羽球選手範例，可點選查看個人檔案'],schedule:['訓練課表','檢視一週訓練並使用選單新增課表'],library:['課表資料庫','24 個熱身、體能、戰術與重建範例'],cycles:['週期管理','以大週期、中週期與小週期掌握訓練重點'],rebuild:['運動機能重建','傷後選手訓練狀態與返場階段']};const [title,sub]=meta[active]
 return <><section className="heading inner-heading"><div><small>大同高中羽球隊 · 測試資料</small><h1>{title}</h1><p>{sub}</p></div>{active==='schedule'&&<button className="primary" onClick={()=>setBuilder(true)}><FiPlus/>新增課表</button>}</section>
 {active==='athletes'&&<AthleteCards list={athletes} select={setSelected}/>} {active==='schedule'&&<Schedule setBuilder={setBuilder}/>} {active==='library'&&<Library setBuilder={setBuilder}/>} {active==='cycles'&&<Cycles/>} {active==='rebuild'&&<Rebuild select={setSelected} flash={flash}/>}</>
}

function Dashboard({team,setTeam,setBuilder,setSelected}:{team:'男生隊'|'女生隊';setTeam:(x:'男生隊'|'女生隊')=>void;setBuilder:(x:boolean)=>void;setSelected:(a:Athlete)=>void}){const list=athletes.filter(a=>a.team===team);return <><section className="heading"><div><small>2026 學年度 · 第 3 週</small><h1>早安，測試教練 👋</h1><p>這是可操作的範例資料，請從左側選單開始體驗。</p></div><button className="primary" onClick={()=>setBuilder(true)}><FiPlus/>新增訓練課表</button></section><section className="metrics"><article><i className="purple"><FiUsers/></i><div><span>範例選手</span><strong>3</strong><small>男生 2 · 女生 1</small></div></article><article><i className="cyan"><FiActivity/></i><div><span>本週平均負荷</span><strong>71<sup>%</sup></strong><small><b>理想區間</b> 65–80%</small></div></article><article><i className="orange"><FiClock/></i><div><span>本週訓練量</span><strong>11<sup> hr</sup></strong><small>5 堂訓練</small></div></article><article><i className="red"><FiHeart/></i><div><span>需關注選手</span><strong>1</strong><small>陳信宇 · 右肩觀察</small></div></article></section><div className="dashboard"><section className="panel weekly"><PanelHead title="本週訓練課表" sub="9 月 7 日 — 9 月 13 日"><TeamSwitch team={team} setTeam={setTeam}/></PanelHead><WeekList setBuilder={setBuilder}/></section><aside className="right"><section className="panel cycle"><PanelHead title="週期進度" sub="秋季聯賽準備期"/><CycleCore/></section><section className="panel recovery"><PanelHead title="選手快速檔案" sub={`${team} · ${list.length} 位`}/>{list.map(a=><button className="person person-button" key={a.id} onClick={()=>setSelected(a)}><i>{a.name[0]}</i><div><strong>{a.name}</strong><span>{a.event} · {a.tags[0]}</span></div><b className={a.status}>{a.status}</b></button>)}</section></aside></div><section className="panel library"><PanelHead title="快速加入訓練模組" sub="點選類別即可開啟課表編輯器"/><LibraryGrid action={()=>setBuilder(true)}/></section></>}

function AthleteCards({list,select}:{list:Athlete[];select:(a:Athlete)=>void}){return <div className="athlete-cards">{list.map(a=><button key={a.id} className="athlete-card" onClick={()=>select(a)}><header><i>{a.name[0]}</i><span className={'status '+a.status}>{a.status}</span></header><h2>{a.name}</h2><p>{a.school} · {a.grade} · {a.event}</p><div className="athlete-kpis"><span><small>訓練負荷</small><b>{a.load}%</b></span><span><small>持拍</small><b>{a.hand}</b></span></div><div className="tags">{a.tags.map(t=><i key={t}>{t}</i>)}</div><footer>查看完整檔案 <span>→</span></footer></button>)}</div>}
function AthleteDetail({athlete:a,onBack}:{athlete:Athlete;onBack:()=>void}){return <><button className="back" onClick={onBack}><FiArrowLeft/>回到選手列表</button><section className="profile-hero"><i>{a.name[0]}</i><div><span>{a.id} · {a.team}</span><h1>{a.name}</h1><p>{a.school} · {a.grade} · {a.event}</p></div><b className={'status '+a.status}>{a.status}</b></section><div className="profile-grid"><section className="panel profile-section"><PanelHead title="基本資料" sub="選手建檔資訊"/><dl><div><dt>身高</dt><dd>{a.height} cm</dd></div><div><dt>體重</dt><dd>{a.weight} kg</dd></div><div><dt>持拍</dt><dd>{a.hand}</dd></div><div><dt>主項</dt><dd>{a.event}</dd></div></dl></section><section className="panel profile-section"><PanelHead title="比賽成績" sub="本年度最佳成績"/><div className="result"><FiTarget/><div><strong>{a.best}</strong><span>範例資料 · 2026</span></div></div></section><section className="panel profile-section"><PanelHead title="健康摘要" sub="測試版僅顯示虛構摘要"/><div className="health"><FiHeart/><span>{a.history}</span></div></section><section className="panel profile-section"><PanelHead title="教練標記" sub="選手特色與訓練重點"/><div className="tags big">{a.tags.map(t=><i key={t}>{t}</i>)}</div></section></div></>}
function Schedule({setBuilder}:{setBuilder:(x:boolean)=>void}){return <section className="panel"><PanelHead title="本週課表" sub="5 堂訓練 · 共 11 小時"/><WeekList setBuilder={setBuilder}/></section>}
function WeekList({setBuilder}:{setBuilder:(x:boolean)=>void}){return <div className="week-list">{sessions.map(s=><article key={s.day}><div className={s.day==='五'?'day today':'day'}><small>週{s.day}</small><strong>{s.date.split('/')[1]}</strong></div><div className="session"><div><span className={'cat '+s.category}>{s.category}</span><strong>{s.title}</strong></div><p><FiClock/> {s.time} · {s.duration} 分鐘</p><footer>{s.blocks.map(x=><i key={x}>{x}</i>)}</footer></div><span className={'level '+s.intensity}><i/>{s.intensity}強度</span><button onClick={()=>setBuilder(true)}><FiEdit3/></button></article>)}</div>}
function Library({setBuilder}:{setBuilder:(x:boolean)=>void}){return <div className="module-sections">{library.map(({key,icon:Icon,color,items})=><section className="panel module-group" key={key}><header><i className={color}><Icon/></i><div><h2>{key}</h2><p>{items.length} 個可用範例</p></div></header>{items.map((item,i)=><button key={item} onClick={()=>setBuilder(true)}><span>{item}</span><small>{i===0?'20':'30'} 分鐘 · RPE {i+3}</small><FiPlus/></button>)}</section>)}</div>}
function LibraryGrid({action}:{action:()=>void}){return <div className="library-grid">{library.map(({key,icon:Icon,color,items})=><button key={key} onClick={action}><i className={color}><Icon/></i><div><strong>{key}</strong><span>{items.length} 個範例</span></div><em>↗</em></button>)}</div>}
function Cycles(){return <div className="cycles-page"><section className="panel cycle-overview"><PanelHead title="大週期 · 2026 秋季賽季" sub="8 月 1 日 — 12 月 20 日"/><div className="macro"><div className="phase p1"><b>體能期</b><span>8/1–9/20 · 7 週</span></div><div className="phase p2"><b>技術期</b><span>9/21–10/25 · 5 週</span></div><div className="phase p3"><b>戰術期</b><span>10/26–11/29 · 5 週</span></div><div className="phase p4"><b>競賽期</b><span>11/30–12/20 · 3 週</span></div></div></section><section className="panel current-cycle"><PanelHead title="目前中週期" sub="體能建立 · 第 3 / 8 週"/><CycleCore/></section><section className="panel micro"><PanelHead title="本週小週期" sub="負荷節奏與訓練主題"/><div>{['中','高','低','高','中','低','休'].map((x,i)=><span key={i}><b>週{['一','二','三','四','五','六','日'][i]}</b><i className={x}>{x}</i></span>)}</div></section></div>}
function CycleCore(){return <><div className="cycle-main"><div className="cycle-ring"><span><b>3</b>/ 8 週</span></div><div><strong>中週期 1</strong><p>體能建立期</p><small>9/1 — 10/25</small></div></div><div className="phases"><span>適應</span><span>建立</span><span>轉換</span><span>競賽</span></div><div className="focus"><small>本週重點</small><strong>下肢力量 · 加速能力</strong><p>體能 45% / 技戰術 55%</p></div></>}
function Rebuild({select,flash}:{select:(a:Athlete)=>void;flash:(x:string)=>void}){const a=athletes[1];return <section className="rebuild-card"><header><i>{a.name[0]}</i><div><span>{a.id} · {a.event}</span><h2>{a.name}</h2><p>右肩過度使用 · 訓練調整中</p></div><b>階段 2 / 4</b></header><div className="rebuild-progress">{['疼痛控制','活動度','力量回復','返場測試'].map((x,i)=><span className={i<2?'done':''} key={x}><i>{i<2?<FiCheck/>:i+1}</i><b>{x}</b></span>)}</div><section><h3>本週重建課表</h3>{['B 肩胛穩定 · 3 組','彈力帶外轉 · 3 × 12','無痛角度米字多球 · 15 分'].map(x=><div key={x}><FiCheck/><span>{x}</span></div>)}</section><footer><button className="secondary" onClick={()=>select(a)}>查看選手檔案</button><button className="primary" onClick={()=>flash('本週重建記錄已在此裝置標記完成')}>完成本週記錄</button></footer></section>}
function TeamSwitch({team,setTeam}:{team:'男生隊'|'女生隊';setTeam:(x:'男生隊'|'女生隊')=>void}){return <div className="switch"><button className={team==='男生隊'?'on':''} onClick={()=>setTeam('男生隊')}>男生隊</button><button className={team==='女生隊'?'on':''} onClick={()=>setTeam('女生隊')}>女生隊</button></div>}
function Builder({blocks,setBlocks,close,flash}:{blocks:string[];setBlocks:React.Dispatch<React.SetStateAction<string[]>>;close:()=>void;flash:(x:string)=>void}){const save=()=>{localStorage.setItem('ams-friday-draft',JSON.stringify(blocks));flash('課表草稿已儲存在這台裝置')};return <div className="modal"><button className="modal-bg" onClick={close}/><section role="dialog" aria-modal="true"><header><div><p>大同高中 · 男生隊</p><h2>新增訓練課表</h2></div><button onClick={close}><FiX/></button></header><main><div className="fields"><label>日期<input type="date" defaultValue="2026-09-11"/></label><label>開始<input type="time" defaultValue="14:00"/></label><label>結束<input type="time" defaultValue="17:00"/></label></div><div className="summary"><FiClock/><div><strong>週五訓練 · 180 分鐘</strong><span>熱身 20 分 · 主訓練 135 分 · 整理 25 分</span></div></div><div className="builder-grid"><div className="picker"><h3>1. 從資料庫加入</h3><p>點選即可加入流程</p>{library.slice(0,5).map(({key,items,icon:Icon,color})=><details key={key} open={key==='熱身'}><summary><i className={color}><Icon/></i><strong>{key}</strong><FiChevronDown/></summary><div>{items.map(item=><button onClick={()=>setBlocks(v=>v.includes(item)?v:[...v,item])} key={item}><FiPlus/>{item}</button>)}</div></details>)}</div><div className="timeline"><h3>2. 訓練流程</h3><p>已選 {blocks.length} 個模組</p>{blocks.map((b,i)=><div className="block" key={b}><i>{i+1}</i><div><strong>{b}</strong><span>{i===0?'熱身 · 20 分':'主訓練 · 30 分'}</span></div><button onClick={()=>setBlocks(v=>v.filter((_,x)=>x!==i))}><FiX/></button></div>)}</div></div></main><footer><span>測試版將草稿保存在本機</span><div><button className="secondary" onClick={save}>儲存草稿</button><button className="primary" onClick={()=>{save();close()}}>建立課表</button></div></footer></section></div>}
function PanelHead({title,sub,children}:{title:string;sub:string;children?:React.ReactNode}){return <header className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div>{children}</header>}
export default App
