import { useMemo, useState } from 'react'
import { FiActivity, FiArrowLeft, FiBarChart2, FiBell, FiCalendar, FiCheck, FiChevronDown, FiClock, FiEdit3, FiGrid, FiHeart, FiLock, FiLogIn, FiMenu, FiPlus, FiSearch, FiSettings, FiShield, FiTarget, FiTrendingUp, FiUser, FiUsers, FiX, FiZap } from 'react-icons/fi'
import './App.css'

type Sport='羽球'|'田徑'|'游泳'
type Athlete={id:string;name:string;sport:Sport;team:'男子組'|'女子組';grade:string;event:string;status:'公開賽事紀錄';load:number;school:string;junior:string;elementary:string;history:string;best:string;resultDate:string;source:string;sourceName:string;tags:string[]}
type Session={day:string;date:string;time:string;title:string;category:string;intensity:'低'|'中'|'高';duration:number;blocks:string[]}

const athletes:Athlete[]=[
 {id:'BD001',name:'劉佳恩',sport:'羽球',team:'男子組',grade:'高中組',event:'男子單打',status:'公開賽事紀錄',load:0,school:'大同高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運男子單打獲第 2 名。其他年度紀錄尚待官方資料逐屆匯入。',best:'113 年全中運高中男子單打第 2 名',resultDate:'2024-04',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_ListGroup.php?LID=202',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['單打','全中運','官方成績']},
 {id:'BD002',name:'吳昌珉',sport:'羽球',team:'男子組',grade:'高中組',event:'男子單打',status:'公開賽事紀錄',load:0,school:'大同高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運男子單打獲第 3 名。技術特徵需由中心檢測與教練訪談後建立。',best:'113 年全中運高中男子單打第 3 名',resultDate:'2024-04',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_ListGroup.php?LID=202',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['單打','全中運','待技術評估']},
 {id:'BD003',name:'周宥翔／張軒瑀',sport:'羽球',team:'男子組',grade:'高中組',event:'男子雙打',status:'公開賽事紀錄',load:0,school:'大同高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運男子雙打冠軍；官方結果以搭檔組合呈現，尚未拆分私人履歷。',best:'113 年全中運高中男子雙打第 1 名',resultDate:'2024-04',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_ListGroup.php?LID=202',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['雙打','全中運冠軍','搭檔紀錄']},
 {id:'AT001',name:'王訢',sport:'田徑',team:'男子組',grade:'高中組',event:'鉛球（6 公斤）',status:'公開賽事紀錄',load:0,school:'大同高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運鉛球決賽投出 17.48 公尺，獲第 1 名。',best:'鉛球 17.48 m · 第 1 名',resultDate:'2024-04-23',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_List.php?LID=101&MID=423',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['鉛球','17.48 m','全中運冠軍']},
 {id:'AT002',name:'姜翊安',sport:'田徑',team:'男子組',grade:'高中組',event:'800 公尺',status:'公開賽事紀錄',load:0,school:'建國中學',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運 800 公尺決賽成績 1:55.11，獲第 1 名。',best:'800 m 1:55.11 · 第 1 名',resultDate:'2024-04-25',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_List.php?MID=425',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['800 公尺','1:55.11','全中運冠軍']},
 {id:'AT003',name:'趙品皓',sport:'田徑',team:'男子組',grade:'高中組',event:'400 公尺跨欄',status:'公開賽事紀錄',load:0,school:'中正高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運 400 公尺跨欄決賽成績 52.95 秒，獲第 3 名。',best:'400 m 跨欄 52.95 · 第 3 名',resultDate:'2024-04-25',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_List.php?MID=425',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['跨欄','52.95 秒','全中運']},
 {id:'SW001',name:'范晴宇',sport:'游泳',team:'女子組',grade:'高中組',event:'50 公尺蛙式',status:'公開賽事紀錄',load:0,school:'西松高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運 50 公尺蛙式決賽成績 33.21 秒，獲第 1 名。',best:'50 m 蛙式 33.21 · 第 1 名',resultDate:'2024-04-22',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_List.php?MID=420',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['蛙式','33.21 秒','全中運冠軍']},
 {id:'SW002',name:'張家瑄',sport:'游泳',team:'女子組',grade:'高中組',event:'200 公尺蝶式',status:'公開賽事紀錄',load:0,school:'松山高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運 200 公尺蝶式決賽成績 2:22.88，獲第 3 名。',best:'200 m 蝶式 2:22.88 · 第 3 名',resultDate:'2024-04',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_List.php?MID=420',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['蝶式','2:22.88','全中運']},
 {id:'SW003',name:'楊庭宜',sport:'游泳',team:'女子組',grade:'高中組',event:'50 公尺蛙式',status:'公開賽事紀錄',load:0,school:'百齡高中',junior:'待本人／學校授權補登',elementary:'待本人／學校授權補登',history:'113 年全中運 50 公尺蛙式決賽成績 33.92 秒，獲第 3 名。',best:'50 m 蛙式 33.92 · 第 3 名',resultDate:'2024-04-22',source:'https://113sport.tp.edu.tw/Module/Score/FinalsReport_List.php?MID=420',sourceName:'113 年全國中等學校運動會官方成績系統',tags:['蛙式','33.92 秒','全中運']},
]
const sessions:Session[]=[
 {day:'一',date:'9/7',time:'16:00–18:30',title:'多球步伐 · 加速',category:'技術',intensity:'中',duration:150,blocks:['動態熱身 B','六點步伐 A','多球進攻 C']},
 {day:'二',date:'9/8',time:'16:00–18:00',title:'下肢力量 · 反應',category:'體能',intensity:'高',duration:120,blocks:['迷你頻帶 B','陷阱硬舉 A','燈號反應 C']},
 {day:'三',date:'9/9',time:'16:00–17:00',title:'恢復與個別課',category:'恢復',intensity:'低',duration:60,blocks:['活動度','呼吸放鬆']},
 {day:'四',date:'9/10',time:'16:00–18:30',title:'攻守轉換 · B 戰術',category:'戰術',intensity:'高',duration:150,blocks:['2 打 1','攻守轉換 B','限制區對抗']},
 {day:'五',date:'9/11',time:'14:00–17:00',title:'敏捷 · 速度 · 技術',category:'混合',intensity:'中',duration:180,blocks:['鬼抓人 C','敏捷階梯 B','10m 加速 A','網前對抗 D']},
]
const library=[
 {key:'熱身',icon:FiActivity,color:'cyan',items:['A 慢跑＋關節活動','B 動態伸展','C 鬼抓人','D 對抽熱身']},
 {key:'敏捷',icon:FiZap,color:'violet',items:['A 六角反應','B 敏捷階梯','C 鏡像移動','D 折返變向']},
 {key:'速度',icon:FiTrendingUp,color:'blue',items:['A 10m 加速','B 羽球步伐衝刺','C 電光起動','D 阻力帶加速']},
 {key:'力量',icon:FiBarChart2,color:'orange',items:['A 陷阱硬舉','B 保加利亞蹲','C 藥球旋轉拋','D 離心弓箭步']},
 {key:'戰術',icon:FiTarget,color:'green',items:['A 拉吊突擊','B 攻守轉換','C 雙打輪轉','D 發接發前三拍']},
 {key:'機能重建',icon:FiHeart,color:'red',items:['A 膝關節控制','B 肩胛穩定','C 踝關節本體感覺','D 返場移動']},
]
const nav=[['dashboard','總覽',FiGrid],['athletes','選手管理',FiUsers],['schedule','訓練課表',FiCalendar],['library','課表資料庫',FiBarChart2],['cycles','週期管理',FiTrendingUp],['rebuild','機能重建',FiHeart]] as const

function App(){
 const [loggedIn,setLoggedIn]=useState(()=>sessionStorage.getItem('ams-demo-login')==='yes');const [active,setActive]=useState('dashboard');const [sport,setSport]=useState<Sport|'全部'>('全部');const [school,setSchool]=useState('全部');const [query,setQuery]=useState('');const [builder,setBuilder]=useState(false);const [mobile,setMobile]=useState(false);const [selected,setSelected]=useState<Athlete|null>(null);const [notice,setNotice]=useState('')
 const [blocks,setBlocks]=useState<string[]>(()=>{const d=localStorage.getItem('ams-friday-draft');try{return d?JSON.parse(d):['C 鬼抓人','B 敏捷階梯','A 10m 加速','D 網前對抗']}catch{return[]}})
 const visible=useMemo(()=>athletes.filter(a=>(sport==='全部'||a.sport===sport)&&(school==='全部'||a.school===school)&&`${a.name}${a.event}${a.tags}${a.school}${a.sport}`.includes(query)),[sport,school,query])
 const enter=()=>{sessionStorage.setItem('ams-demo-login','yes');setLoggedIn(true)};const logout=()=>{sessionStorage.removeItem('ams-demo-login');setLoggedIn(false)}
 const flash=(text:string)=>{setNotice(text);setTimeout(()=>setNotice(''),2200)}
 if(!loggedIn)return <Login onEnter={enter}/>
 return <div className="shell">
  <aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><b><FiActivity/></b><div><strong>運動員管理系統</strong><span>Taipei Sports Science Center</span></div><button onClick={()=>setMobile(false)}><FiX/></button></div><div className="club"><i>北</i><div><span>系統角色</span><strong>臺北市運動科學中心</strong></div></div><nav><small>中心工作台</small>{nav.map(([id,label,Icon])=><button className={active===id?'active':''} key={id} onClick={()=>{setActive(id);setSelected(null);setMobile(false)}}><Icon/><span>{label}</span>{id==='rebuild'&&<i>示範</i>}</button>)}</nav><div className="side-bottom"><button onClick={()=>flash('教學版尚未開放權限管理')}><FiShield/>健康與權限</button><button onClick={()=>flash('系統設定已保留給正式治理版本')}><FiSettings/>系統設定</button><button className="coach" onClick={logout}><i>教</i><div><strong>教學示範帳號</strong><span>點此登出</span></div></button></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>} 
  <main><header className="top"><button className="menu" onClick={()=>setMobile(true)}><FiMenu/></button><label className="search"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋運動、學校、選手或項目…"/></label><button className="bell"><FiBell/></button><span className="sync"><i/>教學版 · 公開賽事資料</span></header><div className="content">{selected?<AthleteDetail athlete={selected} onBack={()=>setSelected(null)}/>:<Page active={active} sport={sport} setSport={setSport} school={school} setSchool={setSchool} athletes={visible} setSelected={setSelected} setBuilder={setBuilder} flash={flash}/>}</div><SiteNotice/></main>
  {notice&&<div className="toast"><FiCheck/>{notice}</div>}{builder&&<Builder blocks={blocks} setBlocks={setBlocks} close={()=>setBuilder(false)} flash={flash}/>} 
 </div>
}

function Login({onEnter}:{onEnter:()=>void}){return <main className="login"><section className="login-copy"><div className="login-brand"><i><FiActivity/></i><strong>運動員管理系統</strong><span>臺北市運動科學中心情境示範</span></div><div><span className="demo-chip">AI 工具教學版 · 非營運系統</span><h1>從公開賽事紀錄，建立<br/>選手歷程與科學支援視角。</h1><p>以臺北市高中羽球、田徑與游泳為資料架構範例，示範中心如何連結選手歷程、檢測方向與訓練資源。</p><div className="login-stats"><span><b>3</b>項運動</span><span><b>9</b>筆官方成績範例</span><span><b>6</b>所學校</span></div><div className="purpose"><FiShield/><p><strong>使用用途聲明</strong>本系統僅提供 AI 工具教學使用，不開放教練或選手後續私下使用，亦不對外提供開放使用，僅供教學用途。</p></div></div><footer>製作單位：臺灣運動健康科技學會 · 教學版 v0.3</footer></section><section className="login-card"><div className="login-icon"><FiUser/></div><span className="eyebrow">中心教學工作台</span><h2>進入系統示範</h2><p>不需要帳號密碼；資料不代表現役完整名單。</p><div className="demo-user"><i>北</i><div><strong>臺北市運動科學中心</strong><span>教學情境 · 唯讀公開資料</span></div><FiCheck/></div><button className="login-button" onClick={onEnter}><FiLogIn/>進入運動員管理系統</button><div className="login-note"><FiLock/><span><strong>隱私邊界</strong>未公開學歷、傷病與檢測資料一律不推測，須經本人及管理單位授權後補登。</span></div></section></main>}

function Page({active,sport,setSport,school,setSchool,athletes:shown,setSelected,setBuilder,flash}:{active:string;sport:Sport|'全部';setSport:(x:Sport|'全部')=>void;school:string;setSchool:(x:string)=>void;athletes:Athlete[];setSelected:(a:Athlete)=>void;setBuilder:(x:boolean)=>void;flash:(x:string)=>void}){
 if(active==='dashboard')return <Dashboard setSelected={setSelected}/>
 const meta:Record<string,[string,string]>={athletes:['臺北市高中選手資料庫','依運動、學校與姓名查詢公開賽事歷史紀錄'],schedule:['運動處方與訓練課表','以中心檢測結果連結運動處方與隊伍訓練'],library:['處方模組資料庫','24 個熱身、體能、戰術與機能重建示範模組'],cycles:['週期管理','用大週期、中週期與小週期銜接學校賽事需求'],rebuild:['中心服務流程','從歷程盤點、檢測到教練協作的教學示範']};const [title,sub]=meta[active]
 return <><section className="heading inner-heading"><div><small>臺北市運動科學中心 · AI 工具教學版</small><h1>{title}</h1><p>{sub}</p></div>{active==='schedule'&&<button className="primary" onClick={()=>setBuilder(true)}><FiPlus/>新增處方課表</button>}</section>
 {active==='athletes'&&<><DatabaseFilters sport={sport} setSport={setSport} school={school} setSchool={setSchool}/><div className="data-scope"><FiShield/><span>目前收錄 113 年全中運臺北市高中選手的 <b>9 筆官方成績範例</b>，不是全市現役完整名單。資料查詢日：2026-09-08。</span></div><AthleteCards list={shown} select={setSelected}/></>} {active==='schedule'&&<Schedule setBuilder={setBuilder}/>} {active==='library'&&<Library setBuilder={setBuilder}/>} {active==='cycles'&&<Cycles/>} {active==='rebuild'&&<CenterFlow flash={flash}/>}</>
}

function Dashboard({setSelected}:{setSelected:(a:Athlete)=>void}){return <><section className="heading"><div><small>城市級運動科學支援 · 教學情境</small><h1>臺北市高中選手歷程總覽</h1><p>從官方成績找到選手，再以授權資料完成檢測、處方與教練協作。</p></div></section><section className="metrics"><article><i className="purple"><FiUsers/></i><div><span>公開成績範例</span><strong>9</strong><small>非現役完整名單</small></div></article><article><i className="cyan"><FiActivity/></i><div><span>示範運動</span><strong>3</strong><small>羽球 · 田徑 · 游泳</small></div></article><article><i className="orange"><FiGrid/></i><div><span>涵蓋學校</span><strong>6</strong><small>依官方賽事單位彙整</small></div></article><article><i className="red"><FiShield/></i><div><span>私人健康資料</span><strong>0</strong><small>未授權不匯入</small></div></article></section><section className="sport-overview">{(['羽球','田徑','游泳'] as Sport[]).map((s,i)=>{const list=athletes.filter(a=>a.sport===s);return <article className={'sport-card sport-'+i} key={s}><header><i>{i===0?'羽':i===1?'徑':'泳'}</i><div><span>高中組</span><h2>{s}</h2></div><b>{list.length} 筆</b></header><p>{[...new Set(list.map(a=>a.school))].join('、')}</p><div>{list.map(a=><button key={a.id} onClick={()=>setSelected(a)}><span>{a.name}</span><small>{a.school} · {a.event}</small><b>→</b></button>)}</div></article>})}</section><section className="panel pathway"><PanelHead title="中心服務判斷路徑" sub="公開歷程不等於醫療結論；到中心後才建立個別化支援"/><div><span><b>1</b>官方賽事歷程<small>確認項目與成績趨勢</small></span><i>→</i><span><b>2</b>本人授權訪談<small>學校歷程、傷病與訓練背景</small></span><i>→</i><span><b>3</b>運動科學檢測<small>依需求選擇體能與技術指標</small></span><i>→</i><span><b>4</b>處方與資源協作<small>與選手、教練共同決策</small></span></div></section></>}

function DatabaseFilters({sport,setSport,school,setSchool}:{sport:Sport|'全部';setSport:(x:Sport|'全部')=>void;school:string;setSchool:(x:string)=>void}){const schools=['全部',...new Set(athletes.filter(a=>sport==='全部'||a.sport===sport).map(a=>a.school))];return <div className="db-filters"><label>運動項目<select value={sport} onChange={e=>{setSport(e.target.value as Sport|'全部');setSchool('全部')}}><option>全部</option><option>羽球</option><option>田徑</option><option>游泳</option></select></label><label>所屬學校<select value={school} onChange={e=>setSchool(e.target.value)}>{schools.map(x=><option key={x}>{x}</option>)}</select></label></div>}

function AthleteCards({list,select}:{list:Athlete[];select:(a:Athlete)=>void}){return <div className="athlete-cards">{list.length?list.map(a=><button key={a.id} className="athlete-card" onClick={()=>select(a)}><header><i>{a.sport[0]}</i><span className="status public">公開紀錄</span></header><h2>{a.name}</h2><p>{a.school} · {a.grade} · {a.event}</p><div className="athlete-kpis"><span><small>運動</small><b>{a.sport}</b></span><span><small>資料日期</small><b>{a.resultDate}</b></span></div><div className="tags">{a.tags.map(t=><i key={t}>{t}</i>)}</div><footer>查看歷程檔案 <span>→</span></footer></button>):<div className="empty">沒有符合目前條件的公開紀錄。</div>}</div>}
function AthleteDetail({athlete:a,onBack}:{athlete:Athlete;onBack:()=>void}){return <><button className="back" onClick={onBack}><FiArrowLeft/>回到選手資料庫</button><section className="profile-hero"><i>{a.sport[0]}</i><div><span>{a.id} · {a.sport} · {a.team}</span><h1>{a.name}</h1><p>{a.school} · {a.grade} · {a.event}</p></div><b className="status public">官方公開賽事紀錄</b></section><div className="profile-grid"><section className="panel profile-section"><PanelHead title="基本與學校歷程" sub="未公開欄位不推測"/><dl><div><dt>目前紀錄單位</dt><dd>{a.school}</dd></div><div><dt>運動／主項</dt><dd>{a.sport} · {a.event}</dd></div><div><dt>過去國中</dt><dd>{a.junior}</dd></div><div><dt>過去國小</dt><dd>{a.elementary}</dd></div></dl></section><section className="panel profile-section"><PanelHead title="賽事與成績" sub="已連結官方原始資料"/><div className="result"><FiTarget/><div><strong>{a.best}</strong><span>{a.resultDate} · <a href={a.source} target="_blank" rel="noreferrer">查看官方來源 ↗</a></span></div></div></section><section className="panel profile-section"><PanelHead title="過去歷程分析" sub="只根據目前已匯入的官方賽事"/><div className="health"><FiTrendingUp/><span>{a.history}</span></div></section><section className="panel profile-section"><PanelHead title="到中心後待建資料" sub="須取得授權並由專業人員建立"/><div className="tags big">{['傷病史訪談','體能測驗','技術／得意技','訓練負荷','檢測方向','運動處方'].map(t=><i key={t}>{t}</i>)}</div><p className="privacy-note">目前沒有私人健康或體能測驗資料；不可由公開成績推定傷病、體能或技術弱點。</p></section></div><section className="source-ledger"><FiShield/><div><strong>來源台帳</strong><span>{a.sourceName} · 賽事日期 {a.resultDate} · 查詢日期 2026-09-08 · 信心：官方已確認</span></div></section></>}
function Schedule({setBuilder}:{setBuilder:(x:boolean)=>void}){return <section className="panel"><PanelHead title="本週課表" sub="5 堂訓練 · 共 11 小時"/><WeekList setBuilder={setBuilder}/></section>}
function WeekList({setBuilder}:{setBuilder:(x:boolean)=>void}){return <div className="week-list">{sessions.map(s=><article key={s.day}><div className={s.day==='五'?'day today':'day'}><small>週{s.day}</small><strong>{s.date.split('/')[1]}</strong></div><div className="session"><div><span className={'cat '+s.category}>{s.category}</span><strong>{s.title}</strong></div><p><FiClock/> {s.time} · {s.duration} 分鐘</p><footer>{s.blocks.map(x=><i key={x}>{x}</i>)}</footer></div><span className={'level '+s.intensity}><i/>{s.intensity}強度</span><button onClick={()=>setBuilder(true)}><FiEdit3/></button></article>)}</div>}
function Library({setBuilder}:{setBuilder:(x:boolean)=>void}){return <div className="module-sections">{library.map(({key,icon:Icon,color,items})=><section className="panel module-group" key={key}><header><i className={color}><Icon/></i><div><h2>{key}</h2><p>{items.length} 個可用範例</p></div></header>{items.map((item,i)=><button key={item} onClick={()=>setBuilder(true)}><span>{item}</span><small>{i===0?'20':'30'} 分鐘 · RPE {i+3}</small><FiPlus/></button>)}</section>)}</div>}
function Cycles(){return <div className="cycles-page"><section className="panel cycle-overview"><PanelHead title="大週期 · 2026 秋季賽季" sub="8 月 1 日 — 12 月 20 日"/><div className="macro"><div className="phase p1"><b>體能期</b><span>8/1–9/20 · 7 週</span></div><div className="phase p2"><b>技術期</b><span>9/21–10/25 · 5 週</span></div><div className="phase p3"><b>戰術期</b><span>10/26–11/29 · 5 週</span></div><div className="phase p4"><b>競賽期</b><span>11/30–12/20 · 3 週</span></div></div></section><section className="panel current-cycle"><PanelHead title="目前中週期" sub="體能建立 · 第 3 / 8 週"/><CycleCore/></section><section className="panel micro"><PanelHead title="本週小週期" sub="負荷節奏與訓練主題"/><div>{['中','高','低','高','中','低','休'].map((x,i)=><span key={i}><b>週{['一','二','三','四','五','六','日'][i]}</b><i className={x}>{x}</i></span>)}</div></section></div>}
function CycleCore(){return <><div className="cycle-main"><div className="cycle-ring"><span><b>3</b>/ 8 週</span></div><div><strong>中週期 1</strong><p>體能建立期</p><small>9/1 — 10/25</small></div></div><div className="phases"><span>適應</span><span>建立</span><span>轉換</span><span>競賽</span></div><div className="focus"><small>本週重點</small><strong>下肢力量 · 加速能力</strong><p>體能 45% / 技戰術 55%</p></div></>}
function CenterFlow({flash}:{flash:(x:string)=>void}){const steps=[['01','歷程盤點','確認官方成績、所屬單位與選手目標'],['02','授權與訪談','由選手／監護人／學校提供必要資料'],['03','需求分流','區分表現、疲勞、傷後回場或技術問題'],['04','檢測設計','選擇體能、生理、生物力學或專項檢測'],['05','共同決策','與教練及選手解讀結果並選擇資源'],['06','處方與追蹤','建立週期、回測指標與必要轉介']];return <><div className="center-flow">{steps.map(([n,t,d])=><button key={n} onClick={()=>flash(`${t}：教學版流程節點`)}><i>{n}</i><div><h2>{t}</h2><p>{d}</p></div><span>→</span></button>)}</div><section className="panel governance"><PanelHead title="資料治理原則" sub="中心角色不是蒐集越多越好，而是只使用有目的、有授權的資料"/><div><span><FiCheck/>公開成績保留來源與日期</span><span><FiCheck/>未成年資料採最小化原則</span><span><FiCheck/>健康資料與一般檔案分開授權</span><span><FiCheck/>AI 不診斷、不補猜缺漏</span></div></section></>}
function Builder({blocks,setBlocks,close,flash}:{blocks:string[];setBlocks:React.Dispatch<React.SetStateAction<string[]>>;close:()=>void;flash:(x:string)=>void}){const save=()=>{localStorage.setItem('ams-friday-draft',JSON.stringify(blocks));flash('教學草稿已儲存在這台裝置')};return <div className="modal"><button className="modal-bg" onClick={close}/><section role="dialog" aria-modal="true"><header><div><p>臺北市運動科學中心 · 教學情境</p><h2>新增運動處方課表</h2></div><button onClick={close}><FiX/></button></header><main><div className="fields"><label>日期<input type="date" defaultValue="2026-09-11"/></label><label>開始<input type="time" defaultValue="14:00"/></label><label>結束<input type="time" defaultValue="17:00"/></label></div><div className="summary"><FiClock/><div><strong>示範訓練 · 180 分鐘</strong><span>熱身 20 分 · 主訓練 135 分 · 整理 25 分</span></div></div><div className="builder-grid"><div className="picker"><h3>1. 從資料庫加入</h3><p>點選即可加入流程</p>{library.slice(0,5).map(({key,items,icon:Icon,color})=><details key={key} open={key==='熱身'}><summary><i className={color}><Icon/></i><strong>{key}</strong><FiChevronDown/></summary><div>{items.map(item=><button onClick={()=>setBlocks(v=>v.includes(item)?v:[...v,item])} key={item}><FiPlus/>{item}</button>)}</div></details>)}</div><div className="timeline"><h3>2. 訓練流程</h3><p>已選 {blocks.length} 個模組</p>{blocks.map((b,i)=><div className="block" key={b}><i>{i+1}</i><div><strong>{b}</strong><span>{i===0?'熱身 · 20 分':'主訓練 · 30 分'}</span></div><button onClick={()=>setBlocks(v=>v.filter((_,x)=>x!==i))}><FiX/></button></div>)}</div></div></main><footer><span>教學版僅將草稿保存在本機</span><div><button className="secondary" onClick={save}>儲存草稿</button><button className="primary" onClick={()=>{save();close()}}>建立課表</button></div></footer></section></div>}
function SiteNotice(){return <footer className="site-notice"><span>製作單位：臺灣運動健康科技學會</span><p>本系統僅提供 AI 工具教學使用，不開放教練或選手後續私下使用，亦不對外提供開放使用，僅供教學用途。</p></footer>}
function PanelHead({title,sub,children}:{title:string;sub:string;children?:React.ReactNode}){return <header className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div>{children}</header>}
export default App
